### ISSUE TITLE
Interested in helping with this module for an idea

### ISSUE THREAD

**Issue by micjevans** [AngryBeaver/beavers-gamepad#3]
@AngryBeaver not sure how else to share my contact information with you but your module here is really fantastic. I have an idea for something I would be willing to assist you develop if it's a direction you think you would like to take this module. 

I used this to run a local session recently and it was a really cool experience. I think it would be really excellent if it was expanded to allow players to take actions. The gist of the concept would be to figure out a way to comfortably map buttons to various actions so players could use their gamepad to perform most of the things they would do at the table (very similar to how console ports work for popular pc games). I've looked into touchvtt, etc, for acting through phones but it just doesn't feel right. As you point out in your mobile module, it takes away from the experience of sitting around a table with other players. The gamepad feels much more natural.

Feel free to contact me by email at micjevans@gmail.com if you'd like help with this.

**Comment by AngryBeaver** [comment]
Hi,

Yes i also think this would be nice which is why i started working on beavers-proximity-action. -> a module that detects actions around your token. in the first edition i plan to have actions like find secret doors, open doors, investigate locations, search for loot, maybe also already find traps. (Actions that interact with walls or grids. ) <- this will take me a huge amount of time
There after the plan is to combine beavers-gamepad with that module. -> here the key problem is 
that i need a way to controll dialog.prompt and selectboxes by a) rotate them to the direction the player is sitting and b) allow gamepad to controll it. Also i think i need a gamepad-module to rotate the token probably the other stick
Then i want to combine it with beavers-crafting to allow quest-giver or anvil tokens. This means i would need to write proximity Actions to interact with tokens.

Then probably a long bug fixing phase followed with gamepad-module ui tweaks (a way to detect axes/buttons by using/pressing the axes/buttons)

So this is my current feature priority and *hopefully will come. (* i am currently unsure about the performance)

As to your request to help with this idea.  I would love to do it on my own as it is less stressfull and more fun then to coordinate a project ( I do this already too much in my real work.)  But thank you for your offer.




What won't come with beavers-proximity-actions is some sort of attack other tokens. As for ranged or area attack this will not fit into proximity actions also it depends too much on system implementation and more important it would need some sort of full automation like in midi-qol. My experience is that it never fits well there is always the extra bonus that is not automatically added and then you are wasting more time fixing things instead of playing. so for me currently it is best to use real dices for attacks especially in gamepad mode (local coop).
